
%% Setup parameter tables

TblVals.Param1 = 1;
TblVals.Param2 = uint8([0; 1]);
TblVals.Param3 = single(10);

Tbl = createCfsTbl(TblVals, 'Tbl');

%% Setup input packets
cellInfo = { 
    { ... 
      'InBus_1_b', ... 
      '', ...
      'No description provided',...
      'Exported', ...
      { ... 
        {'Field1', 8,'uint8'  ,-1,'real','Sample','Fixed',[],[],'',''};...  
        {'Field2', 4,'uint16' ,-1,'real','Sample','Fixed',[],[],'',''};...  
        {'Field3', 2,'single' ,-1,'real','Sample','Fixed',[],[],'',''};... 
        {'Field4', 1,'double' ,-1,'real','Sample','Fixed',[],[],'',''};... 
      } 
    }   
};
Simulink.Bus.cellToObject(cellInfo);
InBus1_s = setupCFSPkt('Tlm');
  
%% Setup output packets
cellInfo = { 
    { ... 
      'OutBus_1_b', ... 
      '', ...
      'No description provided',...
      'Exported', ...
      { ... 
        {'Field1', 8,'uint8'  ,-1,'real','Sample','Fixed',[],[],'',''};...  
        {'Field2', 4,'uint16' ,-1,'real','Sample','Fixed',[],[],'',''};...  
        {'Field3', 2,'single' ,-1,'real','Sample','Fixed',[],[],'',''};... 
        {'Field4', 1,'double' ,-1,'real','Sample','Fixed',[],[],'',''};... 
      } 
    }   
};
Simulink.Bus.cellToObject(cellInfo);
OutBus1_s = setupCFSPkt('Tlm');

cellInfo = { 
    { ... 
      'OutBus_2_b', ... 
      '', ...
      'No description provided',...
      'Exported', ...
      { ... 
        {'Field1', 8,'uint8'  ,-1,'real','Sample','Fixed',[],[],'',''};...  
        {'Field2', 4,'uint16' ,-1,'real','Sample','Fixed',[],[],'',''};...  
        {'Field3', 2,'single' ,-1,'real','Sample','Fixed',[],[],'',''};... 
        {'Field4', 1,'double' ,-1,'real','Sample','Fixed',[],[],'',''};... 
      } 
    }   
};
Simulink.Bus.cellToObject(cellInfo);
OutBus2_s = setupCFSPkt('Tlm');
